### ISSUE TITLE
Why not C++?

### ISSUE THREAD

**Issue by Mazyod** [gameup-io/gameup-ios-sdk#6]
Hello team!

I've been following gameup for a while, it's a really interesting startup! I'm trying to build my own game for a while now, and it's unfortunate that this platform is not ready yet, so I had to write my own backend and client SDK.

The thing is, I chose C++, and looking at your framework, it seems that it provides the same features I would have otherwise used C++ for. I understand C++ can be intimidating, but [with the right libraries](http://pocoproject.org) it is a joy to develop with. The biggest advantage is C++ portability. The code I write on the client is used by iOS, Android, desktop, and even shared with the backend! So, imagine that all the model classes, IAP, Game Session, Matchmaking, ... etc. evolves seamlessly on the front end and backend.

I apologize for this unsolicited question, but I'd be interested to learn your approach, and perhaps you can evaluate C++ as a better option.

Thanks,

**Comment by novabyte** [comment]
Hi @Mazyod,

Thanks for your kind words about our startup. We're working very hard to build an API to help game studios build beautiful social and multiplayer games which work at massive scale.

No need to apologise - you raise a good question. We're not intimidated by C++ although admittedly the team has more practical experience with Java than C++. I have written a compiler in the D language before though; which has a very similar resource allocation and management approach to memory (when the GC is disabled).

We've chosen to use programming languages and runtimes which are specialised for server and client workloads. On the server side we use Erlang a language designed by Ericsson for the telecoms industry. It has great concurrency, can parallelise across CPU cores, enables very clever error handler strategies, and offers very predictable latency.

With the client SDKs so far we've taken the view that it is more helpful to game developers to use native languages for each platform rather than share a codebase in C or C++ and build native bridges from other languages (e.g. with JNI for Android).

Let's move this conversation off the issue tracker. I'm happy to chat through our engineering ideas in more detail with you. You can reach me at chris AT gameup DOT io.

Cheers,

Chris
